# Generated by Django 4.1.1 on 2023-03-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcapp', '0002_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='product',
            new_name='laptop',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='product',
            new_name='laptop',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
